### PR TITLE
Generated JSON database

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
I've generated a JSON database automatically from the Numix Circle theme (not using the latest version of theme)
I've used this script to create the database file 
```python
from os import path, walk
import json

directory = "/usr/share/icons/Numix-Circle/48x48/apps/"
data = {}  # empty JSON data file

for (dirpath, dirnames, filenames) in walk(directory):
    for filename in filenames:
        icon = path.splitext(path.basename(filename))[0]
        if not path.islink(directory + filename):
            if icon not in data.keys():
                data[icon] = {"linux": {"root": icon, "symlinks": []}}
        else:
            real_icon = path.splitext(path.basename(path.realpath(directory + filename)))[0]
            print(real_icon + " - " + icon)
            if real_icon not in data.keys():
                data[real_icon] = {"linux": {"root": real_icon, "symlinks": []}}
            if data[real_icon]["linux"]["root"] != icon:
                data[real_icon]["linux"]["symlinks"].append(icon)

for icon in data:
    root = data[icon]["linux"]
    if len(root["symlinks"]) == 0:
        del data[icon]["linux"]["symlinks"]

with open('saved.json', 'w') as fp:
    json.dump(data, fp, sort_keys=True, indent=4)

```
The next step is adding the Android icons(Hard one :p) After that update the icon theme to have differents sizes

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
We can use the same the script to autogenerate the database file automatically. The only missing part is that we are going to need two csv databases to make the generation automatically from A to Z.

The first one is for Android icons: will contains an icon name and it's symlink in the generated JSON file.
The second one will be the same as Android csv file but for OSX.
Why having those db files? I will update the database generation code to read both files and create a complete JSON database! so if we are going to add Numix Square support for example, we just need to call the script again using the same database files and voila! :)

**Comment by Foggalong** [comment]
I'm confused - where does the CSV come into it?

**Comment by bil-elmoussaoui** [comment]
Well, the JSON file now  is generated using the "Linux" icons, I can't automatically add the android & OSX icons if i don't have their key in the main json database. That's why i think that we should create two simple csv database, if the android/osx icon have an icon that already exists in Linux we add it to the database file with the both icon names; if not we don't, like that we can generate all the themes using one script and add the db files only once. If we do otherwise, we will have to add the icons  for Android and OSX by hand and as you have seen the JSON file has more than 10000 lines... good luck with doing that :P

**Comment by bil-elmoussaoui** [comment]
Sorry i was unsleep when i've said that :p we can use the JSON database for all the themes and the icons can be added to the JSON file instead of adding CSV files, so this can be merged ;)

**Comment by Foggalong** [comment]
I'm not 100% sure whether to merge this straight in or make a new repo for the circle core project. I'll let you know what I decide :+1:

**Comment by bil-elmoussaoui** [comment]
The JSON file can be used for all the icons themes that might be created/updated in the future, as this #10 was merged, if the icon does not exists in the source it won't be generated later ;) 
The next step is to create a circle repo with only source icons without any symlink and start adding different sizes, in the same time i can work on adding support android icons to the database file. What do you think?

**Comment by Foggalong** [comment]
I more mean that this project is clearly exiting the demo phase and entering the alpha stage as an actual product in development. That possibly means moving to a new repo, but I'm not sure yet.

**Comment by bil-elmoussaoui** [comment]
I understand, but i think that the best is to keep the json file with the different scripts on this repo (just changing it's name if possible) and create a new one with only icons. We can modify the script to ask the user to choose bettween the different themes before choosing from the different platforms. But yeah, it's for you to decide :)

**Comment by bil-elmoussaoui** [comment]
I updated the generation code, it now update the existing JSON file correctly
```python
from os import path, listdir
from sys import exit
import json
directory = "/usr/share/icons/Numix-Circle/48x48/apps/"
db = "data.json"

# read the old db file if it exists
if not path.exists(db):
    fw = open(db, "w")
    fw.write("{}")
    fw.close()
fo = open(db)
try:
    data = json.loads(fo.read())
except ValueError:
    if len(fo.read().strip()) == 0:
        data = {}
    else:
        exit("The JSON file is invalid")
fo.close()

for filename in listdir(directory):
    if path.isfile(directory + filename):
        icon = path.splitext(path.basename(filename))[0]
        if not path.islink(directory + filename):
            if icon not in data.keys():
                data[icon] = {"linux": {"root": icon, "symlinks": []}}
        else:
            real_icon = path.splitext(path.basename(path.realpath(directory + filename)))[0]
            if real_icon not in data.keys():
                data[real_icon] = {"linux": {"root": real_icon, "symlinks": []}}
            if data[real_icon]["linux"]["root"] != icon:
                if icon not in data[real_icon]["linux"]["symlinks"]:
                    data[real_icon]["linux"]["symlinks"].append(icon)

# clean empty symlinks keys
for icon in data:
    if data[icon]["linux"]:
        root = data[icon]["linux"]
        if "symlinks" in root.keys() and len(root["symlinks"]) == 0:
            del data[icon]["linux"]["symlinks"]

with open(db, 'w') as fp:
    json.dump(data, fp, sort_keys=True, indent=4)
```

**Comment by Foggalong** [comment]
@bil-elmoussaoui I've stuck the JSON generation code in the [Numix Labs](https://github.com/numixproject/numix-labs/blob/master/Bilal/json-gen.py) repo :)

**Comment by bil-elmoussaoui** [comment]
@Foggalong Great:) is there anything else we must do before creating a proper repo for the new Numix Circle theme?

**Comment by Foggalong** [comment]
It gets a bit complicated from here. Through renaming what is currently the "numix-icon-theme-circle" repo will become the "circle-core" repo, and a new "numix-icon-theme-circle" repo will be created from the result of using the core script. This convoluted swap is so that we can keep the Numix Circle git history while also fixing the PPA problem.

Because of this change it's going to mean finding and rewriting all of the directions as to where people have to report bugs otherwise we're going to have a lot of people turning up in the wrong place :/

**Comment by bil-elmoussaoui** [comment]
Alright, i think adding an issue template will fix this. If there's anything else i can do just ping me here :)

**Comment by Foggalong** [comment]
@bil-elmoussaoui It's not so much the formatting of the issues, it's people reporting issues in the wrong repos which doesn't have an easy fix. We had the same problem when we split Numix into a base theme and an app theme :frowning:

**Comment by Foggalong** [comment]
@bil-elmoussaoui When I run the code to get the latest JSON I get the discrepancies which aren't included in the generated JSON but are in the original theme :/

**Comment by bil-elmoussaoui** [comment]
Can you give me an example? So i can see why its happening? Its might be
due to have an icon symlinked to an other symlink instead of the root icon.

**Comment by Foggalong** [comment]
This is what diff is giving me 
screenshot_2016-06-29_18-15-42
screenshot_2016-06-29_18-15-26

**Pull request merged**
