### PR TITLE
Impelement cairosvg support

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
Things that i added 
* Cairosvg support 
* Create symlinks and png icons directly from the python script (the script folder is unneeded now)
* Clean up the code

The only thing that i didn't understand is this part of the code 
```python
for icon in listdir(odir + "pngs"):
        call(["png2icns", odir + "icns/" + icon.replace(".png", ".icn"),
              odir + "pngs/" + icon], stdout=devnull, stderr=devnull)
```
The code is for converting png icons to icn icons? if so why the icn icons are in the png folder? 
I will modify this part of the code and add it the to the other for!

### CODE REVIEW

**Comment by Foggalong** [comment]
Please split these different changes up into smaller pull requests. Big diffs like this that rewrite a lot of code are difficult to give feedback on :(

**Comment by bil-elmoussaoui** [comment]
Sure i will do today

**Comment by Foggalong** [comment]
:+1:

**Comment by bil-elmoussaoui** [comment]
i will close this, i'm going to create a new pull request soon!

**Pull request closed without merging**
